#!/usr/bin/env bash
# Regenerates the derived copy of the "four rulings" table inside
# wss/docs/annex/WSS.LANE-SYNCHING.md from its canon — the same table in
# skills/lane-record-sync/{SKILL.md,references/*.md}, wherever it
# currently lives (resolved by content, not a pinned path, the same way
# wss-doctor.sh's "Lane tables" check used to).
#
#   bash wss/scripts/wss-gen-lane-rulings.sh          # regenerate and write the annex copy
#   bash wss/scripts/wss-gen-lane-rulings.sh --check  # regenerate to a temp, diff, exit 1 on drift
#
# The canon carries a trailing "— see below" on its last row that is
# intra-document navigation local to the skill's own file (a "### Defer and
# Decline are not the same answer" heading further down); the derived copy
# never carries it, so that suffix is stripped as part of deriving, not left
# to register as a difference.
set -euo pipefail
export LC_ALL=C

SUITE_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)
CANON_DIR="$SUITE_ROOT/skills/lane-record-sync"
TARGET="$SUITE_ROOT/wss/docs/annex/WSS.LANE-SYNCHING.md"
REGEN="bash wss/scripts/wss-gen-lane-rulings.sh"
BEGIN_MARKER='<!-- BEGIN GENERATED by wss-gen-lane-rulings.sh — do not edit by hand -->'
END_MARKER='<!-- END GENERATED -->'

CHECK=0
while [ $# -gt 0 ]; do
  case $1 in
    --check) CHECK=1; shift ;;
    --write) CHECK=0; shift ;;
    *) echo "wss-gen-lane-rulings.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

rulings_rows_() { # file -> "ruling|queue|next" rows, canon's own order, "— see below" stripped
  awk '
    /^\|[[:space:]]*Ruling[[:space:]]*\|[[:space:]]*Files to the queue[[:space:]]*\|[[:space:]]*Next run[[:space:]]*\|/ { t = 1; next }
    t && /^\|[[:space:]]*[-:]/ { next }
    t && /^\|/ {
      n = split($0, f, "|")
      if (n >= 5) {
        r = f[2]; q = f[3]; x = f[4]
        sub(/[[:space:]]*—[[:space:]]*see below[[:space:]]*$/, "", q)
        sub(/[[:space:]]*—[[:space:]]*see below[[:space:]]*$/, "", x)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", r)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", q)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", x)
        print r "|" q "|" x
      }
      next
    }
    t { t = 0 }
  ' "$1"
}

canon=""
for c in "$CANON_DIR/SKILL.md" "$CANON_DIR"/references/*.md; do
  [ -f "$c" ] || continue
  if [ -n "$(rulings_rows_ "$c")" ]; then canon="$c"; break; fi
done
[ -n "$canon" ] || {
  echo "wss-gen-lane-rulings.sh: no '| Ruling | Files to the queue | Next run |' table found under ${CANON_DIR#"$SUITE_ROOT"/} — nothing to derive from" >&2
  exit 1
}

render_table() {
  printf '| Ruling | Files to the queue | Next run |\n|---|---|---|\n'
  rulings_rows_ "$canon" | while IFS='|' read -r r q x; do
    printf '| %s | %s | %s |\n' "$r" "$q" "$x"
  done
}

[ -f "$TARGET" ] || {
  echo "wss-gen-lane-rulings.sh: ${TARGET#"$SUITE_ROOT"/} does not exist" >&2
  exit 1
}
grep -qF "$BEGIN_MARKER" "$TARGET" && grep -qF "$END_MARKER" "$TARGET" || {
  echo "wss-gen-lane-rulings.sh: ${TARGET#"$SUITE_ROOT"/} carries no generated block to replace — add the BEGIN/END GENERATED markers around its four-rulings table first" >&2
  exit 1
}

tmp_table=$(mktemp)
tmp_full=$(mktemp)
trap 'rm -f "$tmp_table" "$tmp_full"' EXIT
render_table >"$tmp_table"

awk -v bf="$tmp_table" -v beginm="$BEGIN_MARKER" -v endm="$END_MARKER" '
  BEGIN { while ((getline l < bf) > 0) block = block l "\n" }
  index($0, beginm) == 1 { print; printf "%s", block; skip = 1; next }
  index($0, endm) == 1   { skip = 0 }
  skip { next }
  { print }
' "$TARGET" >"$tmp_full"

if [ "$CHECK" = 1 ]; then
  if diff "$tmp_full" "$TARGET" >/dev/null; then
    echo "WSS.LANE-SYNCHING.md's four-rulings table current, matches ${canon#"$SUITE_ROOT"/}"
  else
    echo "WSS.LANE-SYNCHING.md's four-rulings table STALE — does not match ${canon#"$SUITE_ROOT"/} — run $REGEN" >&2
    exit 1
  fi
else
  cat "$tmp_full" >"$TARGET"
  echo "wrote ${TARGET#"$SUITE_ROOT"/} from ${canon#"$SUITE_ROOT"/}"
fi
